### ISSUE TITLE
Term negation can't be applied to multi-character symbols (and complement operator is unimplemented)

### ISSUE THREAD

**Issue by dhdaines** [mhulden/pyfoma#27]
In foma/xfst, you can use multi-character symbols in "character classes" and then take the complement of these classes, for example:
```
def U [ u | uː ];
def Unround kw -> k || \U _ .#.;
```
There doesn't seem to be any way to do this in pyfoma without some kind of workaround, transforming `uː` into a single character, for example - I had thought I could use the complement operator `~` but it doesn't appear to be implemented yet.

It's not really clear to me how this *works* in foma since the resulting FSTs have magical `@` symbols in them when you look at them with graphviz or export them as AT&T format, but it does seem to work :)

**Comment by mhulden** [comment]
Term negation `\X `in foma is simply shorthand for `? - X `(`. - X` in PyFoma). That means you can do something like `. - (u|'u:')` for the` \U` in your example.

**Comment by dhdaines** [comment]
Thanks!  I was thinking something like that would be the way to do it... in foma the `\` operator appears to use intersection+complement rather than subtraction, presumably for exactly the reason that it might be applied to strings longer than one symbol:
```c
struct fsm *fsm_term_negation(struct fsm *net1) {
    return(fsm_intersect(fsm_identity(),fsm_complement(net1)));
}
```
It would be good to implement the complement operator since it's mentioned in the documentation, perhaps I can take a shot at it - my understanding of it from the foma code (corroborated by OpenFst: https://www.openfst.org/doxygen/fst/html/complement_8h_source.html) is it's the `complete` operation (create arcs to ensure all labels can be read from every state) plus switching the final states to non-final (accept said arcs and not the original language).

I believe the `.` label in pyfoma already works like the `ρ` in OpenFst, that is it matches any symbol except the ones on the other arcs?

**Comment by mhulden** [comment]
Logically `A & ~B` is the same as `A - B`, but I don't recall why foma used intersection and complementation for the term complement.

Both negation and term negation could be implemented as in the following example:

```python3
def neg(fsm):
    return FST.re(".* - $X", {'X':fsm})

def tneg(fsm):
    return FST.re(". - $X", {'X':fsm})

mycustom = {neg, tneg}

myfst1 = FST.re("$^neg(u|'u:')", functions = mycustom)
myfst2 = FST.re("$^tneg(u|'u:')", functions = mycustom)
```

These could be included as-is as built-in functions. The negation could possibly be a prefix-operator (~) which would require an additional minor change of a line or two in the parser, I believe.

**Comment by dhdaines** [comment]
Makes sense! The prefix-operator `~` for complement is already in the parser (and the documentation), it just doesn't do anything: https://github.com/mhulden/pyfoma/blob/642c3e2f46b8545c04edf7afebcbcb0ee0d2abb4/src/pyfoma/private/regexparse.py#L38

I'll submit a PR...

**Comment by dhdaines** [comment]
Also thank you for the examples!

It turns out that in my specific example, but for rewrite rules in general, the complement operator is not useful.  This took a bit of thinking on my part to understand but is obvious in hindsight - since `~(u | u:)` matches *anything*, including epsilon, the rule will always apply, which is clearly not useful :)

Nonetheless I implemented complement anyway in the PR - the docstring says "FSM", not sure if complement is defined for FSTs or not?
